### ISSUE TITLE
[Bug]: sandbox subscribe no longer triggers onApprove callback

### ISSUE THREAD

**Issue by 8ctopus** [paypal-examples/paypal-dev-support#11] opened 2023-09-28 05:44 UTC
### Contact Details

hello@octopuslabs.io

### Describe the Issue

As of today, the PayPal Sandbox subscription confirmation screen has changed and the onApprove callback in not called when I close the subscription confirmation window. Also confirmation window has no button to return to the business.
Yesterday everything was working so I presume it's changes deployed in the last 24 hours that caused the problem.

Here's my code. It's taken from the official PayPal example.

```html
<!DOCTYPE html>
<head>
<title>store</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<script src="https://www.paypal.com/sdk/js?client-id={{ clientId }}&vault=true&intent=subscription"></script>
<script>

paypal.Buttons({
  style: {
    shape: 'rect',
    color: 'blue',
    layout: 'vertical',
    label: 'subscribe'
  },
  createSubscription: function(data, actions) {
    return actions.subscription.create({
      'plan_id': '{{ planId }}'
    });
  },
  onApprove: function(data, actions) {
    alert('You have successfully subscribed to ' + data.subscriptionID);
  },
  onDecline: function() {
    alert('Something went wrong. Please try again ');
  }
}).render('#paypal-button-container');

</script>
<h1> Subscription plan </h1>
<h2> Sandbox account </h2>
<ul>
  <li> {{ login }} </li>
  <li> {{ password }} </li>
</ul>
<div id="paypal-button-container"></div>
</body>
</html>
```

### Steps To Reproduce

See above

### What type of Operating System are you seeing the problem on?

Windows

### What type of browser are you seeing the problem on?

Edge

### Screenshots or Videos

![image](https://github.com/paypal-examples/paypal-dev-support/assets/13252042/120b4244-6a0d-4fbf-ad46-67e909f0b781)

### Code to produce this issue.

See above

**Comment by stefanosalvucci** [comment] 2023-09-28 13:21
this is happening to us and to @Tronhus also in production environment

**Comment by devchristina** [comment] 2023-09-28 16:43
Additional examples: https://github.com/paypal-examples/paypal-dev-support/issues/11#issue-1916760124

**Comment by seedj** [comment] 2023-09-28 16:57
Following, please give us a feedback ASAP. This is directly impacting our revenue. @devchristina

**Comment by quanbt** [comment] 2023-09-28 17:22
Following

**Comment by seedj** [comment] 2023-09-28 17:22
> Following, please give us a feedback ASAP. This is directly impacting our revenue.

@devchristina

**Comment by devchristina** [comment] 2023-09-28 18:15
I'm being told that this has been fixed, can anyone confirm?

**Comment by JCoupalK** [comment] 2023-09-28 18:28
Our team tested and it seems fixed on our end.

**Comment by seedj** [comment] 2023-09-28 18:37
It's fixed on our side.

**Comment by ra2dev** [comment] 2023-09-28 19:07
@devchristina 
We also encountered an issue where payments were not functioning properly, but it has since been resolved coinciding with the resolution of the current issue.
Could you possibly provide clarification on whether the problem originated from PayPal's end? Any relevant ticket or details would be greatly appreciated. 
Thank you.

**Comment by devchristina** [comment] 2023-09-28 19:12
@ra2dev are these one time payments through checkout? Were you using the same api's? Any more information about the solution would be helpful for me to get answers. _Note: If these answers result in a different product offering, I'll move your question out of this issue to keep the threads clean._

**Comment by ra2dev** [comment] 2023-09-29 09:30
@devchristina 
We have product with subscriptions - it was not working, but I also tested on one time payment - same result.
We used same API, we tested on old/new version of library, also on different accounts, also it reproduced in production and staging *(with sandbox account)

The point is that without any changes it stopped working and after couple of hours it started working again, also without any changes from us.

Issue looked like this:
- user click on paypal button (PayPalButtons from `@paypal/react-paypal-js`) 
- redirects to paypal *(everything passed correct, subscription.create output was correct,  clientId in paypalScriptProvider, etc.)
- on paypal page it allowed user to pay, but at the last step showed: `Things don't appear to be working at the moment. Please try again later.` 


Other notes:
- In logs on paypal page I could see that it get 400 *(check image attached) for `https://www.paypal.com/sdk/js` - it was without client id *(its on payapal page, not smth that we control) as the result there were nullpointer, but it's the consequences, not the cause. 
- onError  in PaypalButtons - was not called, even thought it failed.

![image](https://github.com/paypal-examples/paypal-dev-support/assets/48890185/2556d817-7f0c-4f2d-af1d-4d9ede7fd587)
![image](https://github.com/paypal-examples/paypal-dev-support/assets/48890185/fc845461-3f98-441d-933f-7e9fbdf372d8)

**Comment by devchristina** [comment] 2023-09-29 19:11
Unfortunately, yesterdays' incident was due to changes made on the PayPal side. We have since fixed this problem and are actively working to ensure this doesn't happen again. If you'd like a detailed RCA, please submit a ticket with [Merchant Technical Support](https://www.paypal-support.com/s/?language=en_US).

**Comment by devchristina** [comment] 2023-09-29 19:12
Closing this issue as completed / fixed.

**Closed as completed by devchristina** 2023-09-29 19:12 UTC
Labels: bug, api

**Comment by seedj** [comment] 2023-10-01 18:37
@devchristina we are facing randomly this issue again. Please can you check the status? Otherwise, we'll be forced to change the gateway early next week.
